Cargo.toml, examples/demo.rs, src/dispatcher.rs, src/lib.rs
This is a PR to make tui-logger compatible with tui-rs v0.9.x. My goal is to not only make it compile and function, but also to make a few changes to the code-base as possible; so you may choose a different set of changes.  There were a number of small changes mostly related to the tui-rs change from using `Widget::render` to  `Frame::render_widget`.
The biggest change was a change to  the builder pattern for some widgets to claim ownership of the struct rather than a borrow. This was made b/c the the new render_widget function required to take ownership of the widget, so it seems cleaner to alter the builder pattern.
=> Bump tui-rs dep to v0.9

Cargo.toml, README.md, examples/demo.rs, src/dispatcher.rs, src/event/crossterm_impl.rs, src/event/termion_impl.rs, src/lib.rs
This upgrades `tui-rs` to v0.10 and also add support for the `crossterm` backend so that it can be used on Windows (which `termion` does not support). The backend can be selected via Cargo feature flags.
When running the example on Windows with the crossterm backend, the highlights won't be applied unless [this patch](https://github.com/fdehau/tui-rs/pull/368) is included in tui-rs.
Note: I've added some info regarding the crossterm backend to the readme. It references `tui-logger` version `0.4`. However, since this PR bumps the dependency version, the version of this crate should be bumped to `0.5`. The readme will then also needs to be updated.
=> Upgrade to tui v0.10 and add crossterm support

src/lib.rs
Currently, the signature for TuiLoggerWidget::state is 
`pub fn state(&'b mut self, state: &TuiWidgetState) -> &mut TuiLoggerWidget<'b>` 
which mutably borrows the widget for the remainder of its lifetime. This prevents the widget from being moved and drawn. By removing the explicit lifetime on `&mut self`, the borrow is limited to the lifetime of the returned borrow.
Without this change, I wasn't able to use this widget - it works now!
Thanks
=> Elide receiver lifetime on TuiLoggerWidget::state()

src/lib.rs
My application uses a separate UI thread, which requires `TuiWidgetState` to implement `Send`. This PR "upgrades" all `Rc`s and `RefCell`s to their thread-safe alternatives.
Note: I have not adjusted the semver yet!
=> Fix: allow `TuiWidgetState` to be sent over threads

Cargo.toml
tui had another breaking release, which unfortunately means that anything building on top that new version (e.g. latest tuirealm 1.6) isn't compatible with tui-logger anymore. Fortunately, tui-logger seems to be unaffected by that breaking release, so this PR just bumps to the next major.
=> Update to latest tui dependency

Cargo.toml, src/lib.rs
Adds support for a simple externally accessible `Drain` interface inspired by but independent from slog. The example shows how to easily use it together with `env_logger`, falling back to it for filtering and alike.
=> Add Drain for customized logging support

Cargo.toml, src/lib.rs, src/tracing_subscriber.rs
This PR provides a `tracing_subscriber::Layer` implementation for recording log events in applications that use the `tracing` crate for logging.
=> Add support for tracing-subscriber

src/lib.rs
This PR makes it possible to set the border type for the smart widget.
=> Support setting `BorderType` for `TuiLoggerSmartWidget`

src/lib.rs
This PR adds [`Eq`](https://doc.rust-lang.org/std/cmp/trait.Eq.html) implementation for `TuiWidgetEvent`.
I personally need this for testing (asserting the enum fields) in my application.
=> Implement `Eq` for `TuiWidgetEvent`

Cargo.toml
To avoid bringing `time` v0.1.x into dependency graph, see https://github.com/time-rs/time/issues/293
Fixes #36
=> Disable default features of `chrono`

Cargo.toml, examples/demo.rs, src/lib.rs
updated ratatui version to 0.22 and fixed clippy warnings
=> Update ratatui version

.github/workflows/build_examples.yml, Cargo.toml, README.md, examples/demo.rs, src/lib.rs
=> remove tui-support, upgrade to ratatui 0.24.0

src/lib.rs
tui-logger directly replaces `symbol` field of `Cell`. However there is more efficient API `Cell::set_symbol`. This method reuses the heap buffer in `String` so reallocation doesn't happen.
=> Use `Cell::set_symbol` for better heap handling

Cargo.toml
I was having issues with version mismatch in my project using `ratatui` `0.25.0`, so had to upgrade it.
Fixes #53
=> Upgrade ratatui to 0.25.0

.github/workflows/build_examples.yml, Cargo.toml, bacon.toml, examples/demo.rs, src/lib.rs
Updated the demo example to use features from the latest version of the
`ratatui` crate and simplified the application model significantly. Note
that the main crate is still compatible with `ratatui` version `0.25.0`,
but the demo example uses features from `0.26.0`.
Moved the optional dependencies on `termion` and `crossterm` to the
`dev-dependencies` section of the `Cargo.toml` file, and made them
mutually exclusive in the demo example. Moved the backend specific code
into seperate modules.
To run the demo, use either of the following commands:
```shell
cargo run --example demo --features crossterm
cargo run --example demo --features termion
```
Added a bacon config file to make it easy to check that the demo
compiles with the `crossterm` and `termion` features enabled.
---
Note: …
=> Update and simplify demo example

examples/demo.rs, src/lib.rs
These enums are small and simple enough to be `Copy`. This change
simplifies calling code to not have to use `&` when passing or
comparing these enums.
See https://doc.rust-lang.org/std/marker/trait.Copy.html#when-should-my-type-be-copy
for justification.
BREAKING CHANGE: `TuiWidgetEvent::transition()` method now takes a
`TuiWidgetEvent` by value instead of by reference.
=> feat!: derive `Copy` on TuiWidgetEvent and TuiLoggerLevelOutput

.github/workflows/semver_checks.yml
This PR implements a simple cargo-semver-checks github action that will run on push/PR to this repo. I considered the alternative of only running this action on publish but I was not sure what your workflow is.
You can test this locally using nektos/act - the full size docker image option is required.
=> Implement Cargo Semver Checks github action - resolves #62

Cargo.toml, src/lib.rs, src/tracing_subscriber.rs
Closes #67.
1. Utilises the `doc_cfg` attribute to show documentation for non-default docs by default on docs.rs. This also benefits the `slog` feature. https://users.rust-lang.org/t/how-to-document-optional-features-in-api-docs/64577
2. Added some implementation information and information about #66 to the pre-existing docs
This will build as expected on docs.rs with no additional effort as they run nightly rust. However, to build docs locally, you will need to run the following command to mimic docs.rs environment.
```
cargo +nightly rustdoc -p tui-logger --all-features -- --cfg docsrs
```
Here's an example of the new page for `TuiTracingSubscriberLayer`
=> Add docs for tracing_subscriber/slog

Cargo.toml, src/lib.rs, src/tracing_subscriber.rs
Noticed with 0.14.0, `tui_logger::init()` is now used to set log level when using tracing. This is nice because I can now use different log levels than the old default (info or higher).
I have updated the docs to remove the 'limitation' I added previously in #68 as it has been resolved.
I also added `log::LevelFilter` as a re-export, as it is required as a parameter to `init()`, and tracing users are not likely to import `log`. This should be a non-breaking change as far as I am aware, `log` users can continue to use `log::LevelFilter` and tracing users can start using `tui_logger::LevelFilter` and I have tested this locally.
Finally, version num has been bumped to match crates.io.
=> Re-export log::LevelFilter and update docs to match

src/lib.rs, src/tracing_subscriber.rs
- switch HashMap to BTreeMap to ensure keys are always in the same order
Before:
After:
=> fix formatter for tracing events

examples/demo.rs, src/lib.rs
This adds the capability to format the log dumping to a file. 
No filtering is added in this.
I also feel tempted to refactor the code to have a format Options time for all the loggers to share, so the actual formatting code can be extracted and reused. But I didn't want to write a huge PR without seeing if this is generally a welcomed idea.
=> give file logging format options

Cargo.toml, src/widget/smart.rs, src/widget/standard_formatter.rs
Previously if a unicode char that was longer then 1 byte was split the whole program panicked.
test case:
add 
```rust
error!(target: "background-task", "これは日本語の誤りですこれは日本語の誤りです");
```
to background task in the demo. You may need to resize you terminal to get it to split.
This pull request would fix this issue.
However the character might not be displayed correctly because they may be bigger then normals ones, in my case they are exactly twice as large. I don't see this as a big issue but I felt like I should mention it.
=> Split lines safely

.github/workflows/cargo_test.yml, src/tracing_subscriber.rs
Hi there, I noticed in #87 that `tui_logger::tracing_subscriber_layer()` was removed from the public API accidentally in a previous refactoring.
I think that's not a bad thing since the function didn't really do anything and just constructed a literal `TuiTracingSubscriberLayer`.
So I'm proposing in this PR to remove `tui_logger::tracing_subscriber_layer()` and update the docs to reflect users should use `TuiTracingSubscriberLayer` directly.
It looks like this would have been picked up by the doctest but it requires the feature enabled to run in CI, so have added that step.
=> docs: Fix invalid docs for TuiTracingSubscriberLayer (#87)
